### ISSUE TITLE
Booster cant be teleported back

### ISSUE THREAD

**Issue by Pryan1kk** [MrHydralisk/Lethal-Company-Enhanced-Radar-Booster#19] opened 2024-05-27 12:49 UTC
Inverse teleport works great but booster cant be teleport back

**Comment by MrHydralisk** [comment] 2024-05-27 13:35
Unless you provide me with enough information to reproduce this issue on my end, there is not much what I can tell you. It include log errors that indicate not being able to teleport it or exact course of actions that you did to get this issue. Additionally settings file information also would be nice to have.

**Comment by Pryan1kk** [comment] 2024-05-27 13:54
> Unless you provide me with enough information to reproduce this issue on my end, there is not much what I can tell you. It include log errors that indicate not being able to teleport it or exact course of actions that you did to get this issue. Additionally settings file information also would be nice to have.

Its just cant be teleported back 
Can you just check it? I dont have any mod skills or something like that

**Comment by MrHydralisk** [comment] 2024-05-27 14:10
Currently I not playing LC. v50 was tested and updated to it, so it was working unless they drop like new version already. It was tested by multiple players from LC Modding Discord server and no such issue was reported. That's why I was asking for additional info, since it not suppose to happen, unless something interfering.

**Comment by Pryan1kk** [comment] 2024-05-27 14:30
> Like for example last time someone reported it not working it end up being other mod LCGoldScrap, that was causing error, which was preventing this ERB mod working properly. All it took is to figure out the reason and report to proper mod dev and it was fixed in few days on their side.

Okay, how to check these errors?

**Comment by MrHydralisk** [comment] 2024-05-27 14:35
C:\Users\...\AppData\LocalLow\ZeekerssRBLX\Lethal Company find file Player.log. It collect information about last played session since you open the game and till you close it. If some error happens in between it write inside of it.
As for config MrHydralisk.EnhancedRadarBooster.cfg from Game folder Lethal Company\BepInEx\config.
Plus tell me: 
* if you experienced it in solo game or when playing with someone?
* if you were the host of the lobby or joined someone else?
* If everyone have ERB installed in a lobby?

**Comment by Pryan1kk** [comment] 2024-05-27 14:45
> MrHydralisk.EnhancedRadarBooster.cfg
i played with someone
i wasnt host
yes

in logs i seen only "Sending config sync request to Server" and "Receiving config sync from Server" no errors
let me try in solo game, i think it was bad lobby

**Comment by MrHydralisk** [comment] 2024-05-27 14:47
You can send the filles itself, so you don't need to search through them.

**Comment by Pryan1kk** [comment] 2024-05-27 14:54
is solo it dont work too
[Player.log](https://github.com/MrHydralisk/Lethal-Company-Enhanced-Radar-Booster/files/15457398/Player.log)

**Comment by MrHydralisk** [comment] 2024-05-27 15:05
Okay, I can see that it doesn't seems to be error can be noticed. The question is:
* Do you have any idea if you have any more that might change Radar Booster, Teleportation or Monitor target selection (aka how you select Radar Booster for teleportation with a button before teleportation)?
* Do you know which mod logging this?
> radar target index 3
> radar target index 4
> radar target index 5
> radar target index 6
* Could you try launching solo for testing without ainavt.lc.lethalconfig and viviko.ItemClippingFix and MV.NicerTeleporters?

**Comment by MrHydralisk** [comment] 2024-05-27 15:07
Actually, now when I checked MV.NicerTeleporters it just rewriting teleportation code, so it highly possible that that mod preventing Radar Booster telportation, due to not mod compatability friendly way of patching teleportation.

**Comment by MrHydralisk** [comment] 2024-05-27 15:10
If you test without it and Radar Boosters will teleport properly, then we found the culprit.

**Comment by Pryan1kk** [comment] 2024-05-27 15:18
yea this was a conflict between NiceTeleporters

**Comment by MrHydralisk** [comment] 2024-05-27 15:25
Good thing we figured it this easy. It pretty common esp in LC. Saw a lot of modders making their idea via patch by replacing vanilla code fully, which works perfect, when you use only that mod A. But once there is another mod B that trying to access that vanilla code, it never able to get it, due to overriding it by A. It usually require some drastic changes of a way how they trying to patch the vanilly cone on a side of A. But you lucky that there is already alternatives to it, so can just replace the NicerTeleporters with BetterTeleporter in your modpack and should be able to return playing without issues.

**Closed by MrHydralisk** 2024-05-27 15:25 UTC
Labels: good first issue

**Comment by Pryan1kk** [comment] 2024-05-27 15:26
thanks for help
have a nice day
